USE Docs

CREATE TABLE Usuario
(
	EntidadeID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	Nome VARCHAR(60) NOT NULL,
	Sobrenome VARCHAR(60),
	Email VARCHAR(80) NOT NULL,
	DataNascimento DATE,
	Avatar VARCHAR(50),
	DataModificacao DATE NOT NULL
)

CREATE TABLE Senha 
(
	EntidadeID INT NOT NULL PRIMARY KEY FOREIGN KEY REFERENCES Usuario(EntidadeID),
	SenhaHash VARCHAR(30) NOT NULL,
	DataModificacao DATE NOT NULL
)

CREATE TABLE Perfil 
(
	EntidadeID INT NOT NULL PRIMARY KEY FOREIGN KEY REFERENCES Usuario(EntidadeID),
	Nome VARCHAR(30) NOT NULL,
	CodigoPerfil CHAR(2) NOT NULL,
	DataModificacao DATE NOT NULL
)

CREATE TABLE Projeto
(
	EntidadeID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY, 
	GerenteID INT NOT NULL FOREIGN KEY REFERENCES Usuario(EntidadeID),
	Nome VARCHAR(80), 
	DataInicio DATE NOT NULL,
	DataTermino DATE NOT NULL,
	StatusProjeto BIT NOT NULL,
	DataModificacao DATE NOT NULL
)

CREATE TABLE Prazo 
(
	EntidadeID INT NOT NULL PRIMARY KEY FOREIGN KEY REFERENCES Projeto(EntidadeID),
	Horas SMALLINT NOT NULL,
	Classificacao VARCHAR(40),
	DataModificacao DATE NOT NULL
)

CREATE TABLE Etapa
(
	EtapaID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	Nome VARCHAR(70), 
	DataInicio DATE NOT NULL,
	DataTermino DATE NOT NULL,
	StatusEtapa BIT NOT NULL,
	DataModificacao DATE NOT NULL
)

CREATE TABLE Projeto_x_Etapa
(
	ProjetoEntitdadeID INT NOT NULL FOREIGN KEY REFERENCES Projeto(EntidadeID),
	EtapaID INT NOT NULL FOREIGN KEY REFERENCES Etapa(EtapaID)
)

CREATE TABLE Documento 
(
	DocumentoID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	AutorID INT NOT NULL FOREIGN KEY REFERENCES usuario(entidadeID),
	Nome VARCHAR(70) NOT NULL,
	Extensao CHAR(10),
	DataInclusao DATE NOT NULL,
	DataModificacao DATE NOT NULL
)

CREATE TABLE Documento_x_Etapa
(
	DocumentoID INT NOT NULL FOREIGN KEY REFERENCES Documento(DocumentoID),
	EtapaID INT NOT NULL FOREIGN KEY REFERENCES Etapa(EtapaID)
)